In [1]:
pip install numpy


     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     --------------------------------- ------ 51.2/61.0 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 461.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.5 MB 1.7 MB/s eta 0:00:10
   ---------------------------------------- 0.1/15.5 MB 950.9 kB/s eta 0:00:17
    --------------------------------------- 0.2/15.5 MB 1.1 MB/s eta 0:00:14
    --------------------------------------- 0.2/15.5 MB 1.1 MB/s eta 0:00:14
    --------------------------------------- 0.3/15.5 MB 886.2 kB/s eta 0:00:18
    --------------------------------------- 0.4/15.5 MB 998.3 kB/s eta 0:00:16
    --------------------------------------- 0.4/15.5 MB 998.3 kB/s eta 0:00:16
   - -------------------------------------- 0.4/15.5 MB 757.8 kB/s eta 0:00:20
   - -------------------------------------- 0.4/15.5 MB 710.6 kB/s eta 

In [2]:
import numpy as np

In [5]:
pip install pandas


   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.5 MB 365.7 kB/s eta 0:00:32
   ---------------------------------------- 0.1/11.5 MB 479.1 kB/s eta 0:00:24
   ---------------------------------------- 0.1/11.5 MB 393.8 kB/s eta 0:00:29
   ---------------------------------------- 0.1/11.5 MB 405.9 kB/s eta 0:00:28
    --------------------------------------- 0.2/11.5 MB 420.1 kB/s eta 0:00:27
    --------------------------------------- 0.2/11.5 MB 515.5 kB/s eta 0:00:22
    --------------------------------------- 0.2/11.5 MB 515.5 kB/s eta 0:00:22
   - -------------------------------------- 0.3/11.5 MB 528.4 kB/s eta 0:00:22
   - -------------------------------------- 0.3/11.5 MB 528.4 kB/s eta 0:00:22
   - -------------------------------------- 0.4/11.5 MB 534.1 kB/s eta 0:00:21

In [7]:
pip install seaborn

   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   -- ------------------------------------ 20.5/294.9 kB 217.9 kB/s eta 0:00:02
   -------- ------------------------------ 61.4/294.9 kB 825.8 kB/s eta 0:00:01
   -------- ------------------------------ 61.4/294.9 kB 825.8 kB/s eta 0:00:01
   -------- ------------------------------ 61.4/294.9 kB 825.8 kB/s eta 0:00:01
   -------- ------------------------------ 61.4/294.9 kB 825.8 kB/s eta 0:00:01
   -------- ------------------------------ 61.4/294.9 kB 825.8 kB/s eta 0:00:01
   --------------- ---------------------- 122.9/294.9 kB 288.8 kB/s eta 0:00:01
   --------------- ---------------------- 122.9/294.9 kB 288.8 kB/s eta 0:00:01
   --------------- ---------------------- 122.9/294.9 kB 288.8 kB/s eta 0:00:01
   ----------------------- -------------- 184.3/294.9 kB 293.6 kB/s eta 0:00:01
   ----------------------- -------------- 184.3/294.9 kB 293.6 kB/s eta 0:00:01
   ----------------------------- -------- 225.3/2

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.


In [11]:
x = np.arange(1,50,4)
x

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [12]:
x=np.array([1,2,3,5,4])
x,type(x)

(array([1, 2, 3, 5, 4]), numpy.ndarray)

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.one([2,2])


AttributeError: module 'numpy' has no attribute 'one'

In [15]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
y=np.array([1,2,3,4,5])
print(y,type(y))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [17]:
y.ndim


1

In [19]:
ar=np.array([1,2,3,5],ndmin=10)
ar.ndim

10

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
np.empty((4,2))

array([[1.48219694e-323, 2.12199579e-314],
       [2.12199579e-314, 6.36598737e-314],
       [8.48798316e-314, 4.24399158e-314],
       [4.24399158e-314, 2.12199579e-314]])

In [26]:
np.arange((100,10))

TypeError: arange: scalar arguments expected instead of a tuple.

In [27]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
k