In [1]:
import numpy as np

In [7]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
b=np.array([[22,3,4,5],[5,6,3,9]])
b

array([[22,  3,  4,  5],
       [ 5,  6,  3,  9]])

In [15]:
b.ndim
b.shape

(2, 4)

In [17]:
b.dtype

dtype('int32')

In [18]:
a.nbytes

16

In [20]:
c=np.array([[2,8,0,1,2,3,4,5,6],[5,6,3,2,8,9,3,9,7]])
c

array([[2, 8, 0, 1, 2, 3, 4, 5, 6],
       [5, 6, 3, 2, 8, 9, 3, 9, 7]])

In [27]:
c[1,4]*4
print(c[1,:])#all numbers in a particular row
print(c[:,5])#all numbers in a partivular row and specific columns from of 1st

[5 6 3 2 8 9 3 9 7]
[3 9]


In [35]:
d=np.array([[[[1,2],[3,4],[5,6],[7,8]]]])
d

array([[[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]]])

In [36]:
d.ndim

4

In [38]:
s=np.ones((2,3,4)) #for one numbers
#for zeros we use np.zeros((2,3))
s

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [39]:
#for identity matrix
z=np.identity(5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
a=np.array([1,2,4,5])
b=a.copy()
b[0]=12
print(b)
print(a+2)

[12  2  4  5]
[3 4 6 7]
